#include <iostream>
#include "parser.tab.h"  // Generated by Bison

// Declare external variables/functions from Flex
extern int yylex();
extern int yyparse();
extern FILE* yyin;

// Flex function to clean up
extern void yyterminate();

int main(int argc, char* argv[]) {
    // Check if an input file is provided
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <input_file>" << std::endl;
        return 1;
    }

    // Open the input file
    FILE* input_file = fopen(argv[1], "r");
    if (!input_file) {
        std::cerr << "Error: Unable to open file " << argv[1] << std::endl;
        return 1;
    }

    // Set Flex to read from the file
    yyin = input_file;

    // Parse the input
    std::cout << "Parsing the input..." << std::endl;
    yyparse();

    // Clean up and close the file
    fclose(input_file);

    return 0;
}
